# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install postgresql
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'postgresql'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ig-fr_development

production:
  <<: *default
  database: ig-fr_production
  username: ig-fr
  password: <%= ENV['IG-FR_DATABASE_PASSWORD'] %>
